# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CdC6UHHPNwpr6FQC5BuFLyEYp5oHjWeC
"""

# ==========================================================
# Application Name: gradio_app_cardiovascular_project.py
# Description: CVD Analytics & Decision System -- reads S3 Silver layer
#              directly and trains entirely in-session (no SageMaker
#              endpoint dependency).
# ==========================================================

# 1. Install required packages in Google Colab
!pip install -q gradio pandas scikit-learn seaborn matplotlib pyarrow boto3 scipy

import os
import re
import io
import json
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import HistGradientBoostingClassifier, HistGradientBoostingRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

import gradio as gr
import boto3
from botocore.exceptions import ClientError

# ==========================================================
# 1a. AWS CREDENTIALS (Colab Secrets)
# ==========================================================
try:
    from google.colab import userdata
    AWS_KEY_COLAB = userdata.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_COLAB = userdata.get('AWS_SECRET_ACCESS_KEY')
    print("✅ Successfully retrieved AWS credentials from Google Colab Secrets.")
except Exception as e:
    AWS_KEY_COLAB = None
    AWS_SECRET_COLAB = None
    print("⚠️ Could not load AWS credentials from Google Colab Secrets. Ensure notebook access is enabled.")

AWS_REGION = "us-east-1"
S3_BUCKET = "mgmt-healthcare-analytics-jrms-final-project"
S3_SILVER_PREFIX = "patient-data/silver"
S3_MODEL_PREFIX = "gradio-app/models"  # where trained artifacts are cached back to S3

s3_client = boto3.client(
    's3',
    region_name=AWS_REGION,
    aws_access_key_id=AWS_KEY_COLAB,
    aws_secret_access_key=AWS_SECRET_COLAB
)

# ==========================================================
# 2. DATA INGESTION -- READ DIRECTLY FROM S3 SILVER LAYER
# ==========================================================
def load_dataset_from_s3():
    """Read every parquet part-file under the Silver prefix directly from S3."""
    print(f"Loading dataset from s3://{S3_BUCKET}/{S3_SILVER_PREFIX}/ ...")
    paginator = s3_client.get_paginator('list_objects_v2')
    parts = []
    for page in paginator.paginate(Bucket=S3_BUCKET, Prefix=f"{S3_SILVER_PREFIX}/"):
        for obj in page.get('Contents', []):
            key = obj['Key']
            if key.endswith('.parquet'):
                parts.append(key)

    if not parts:
        raise FileNotFoundError(
            f"No .parquet files found under s3://{S3_BUCKET}/{S3_SILVER_PREFIX}/ "
            f"-- check the bucket/prefix and that your AWS credentials have s3:ListBucket "
            f"and s3:GetObject permissions on this path."
        )

    frames = []
    for key in parts:
        body = s3_client.get_object(Bucket=S3_BUCKET, Key=key)['Body'].read()
        frames.append(pd.read_parquet(io.BytesIO(body)))
    df_out = pd.concat(frames, ignore_index=True)
    print(f"Loaded {len(df_out)} records from {len(parts)} S3 part-file(s).")
    return df_out

df_raw = load_dataset_from_s3()

# ==========================================================
# 3. SCHEMA CLEANUP -- GlueParquet column-suffix handling
# ==========================================================
# The Silver layer is written by AWS Glue's "glueparquet" format, which
# appends #N suffixes to most columns (e.g. 'Systolic_BP#12'). Clean those
# back to the display names the rest of this app expects.
column_mapping = {}
for c in df_raw.columns:
    clean_c = re.sub(r'#\d+$', '', c)
    c_lower = clean_c.lower().replace('_', ' ').strip()

    if 'sex' in c_lower: column_mapping[c] = 'Sex'
    elif 'weight' in c_lower and 'was' not in c_lower: column_mapping[c] = 'Weight (kg)'
    elif 'height' in c_lower and 'm' in c_lower and 'was' not in c_lower and 'cm' not in c_lower: column_mapping[c] = 'Height (m)'
    elif 'height' in c_lower and 'cm' in c_lower and 'was' not in c_lower: column_mapping[c] = 'Height (cm)'
    elif c_lower == 'bmi': column_mapping[c] = 'BMI'
    elif 'abdominal' in c_lower and 'was' not in c_lower: column_mapping[c] = 'Abdominal Circumference (cm)'
    elif 'waist' in c_lower and 'was' not in c_lower: column_mapping[c] = 'Waist-to-Height Ratio'
    elif 'systolic' in c_lower and 'was' not in c_lower: column_mapping[c] = 'Systolic BP'
    elif 'diastolic' in c_lower and 'was' not in c_lower: column_mapping[c] = 'Diastolic BP'
    elif 'blood pressure category' in c_lower: column_mapping[c] = 'Blood Pressure Category'
    elif ('total' in c_lower or 'cholesterol' in c_lower) and 'was' not in c_lower: column_mapping[c] = 'Total Cholesterol (mg/dL)'
    elif 'hdl' in c_lower and 'was' not in c_lower: column_mapping[c] = 'HDL (mg/dL)'
    elif 'ldl' in c_lower and 'was' not in c_lower: column_mapping[c] = 'Estimated LDL (mg/dL)'
    elif ('sugar' in c_lower or 'fasting' in c_lower) and 'was' not in c_lower: column_mapping[c] = 'Fasting Blood Sugar (mg/dL)'
    elif 'smok' in c_lower: column_mapping[c] = 'Smoking Status'
    elif 'diabe' in c_lower and 'was' not in c_lower: column_mapping[c] = 'Diabetes Status'
    elif 'activity' in c_lower or 'physical' in c_lower: column_mapping[c] = 'Physical Activity Level'
    elif 'family' in c_lower or 'history' in c_lower: column_mapping[c] = 'Family History of CVD'
    elif 'level' in c_lower and 'risk' in c_lower: column_mapping[c] = 'CVD Risk Level'
    elif 'score' in c_lower and 'risk' in c_lower and 'was' not in c_lower: column_mapping[c] = 'CVD Risk Score'

df_raw = df_raw.rename(columns=column_mapping)

# ==========================================================
# 4. SCHEMA DEFINITION (ALL 35 PARQUET FIELDS)
# ==========================================================
demographic_cols = ['Sex', 'Age']
anthropometric_cols = ['Weight (kg)', 'Height (m)', 'Height (cm)', 'BMI', 'Abdominal Circumference (cm)', 'Waist-to-Height Ratio']
vitals_cols = ['Systolic BP', 'Diastolic BP', 'Blood Pressure Category']
biochemical_cols = ['Total Cholesterol (mg/dL)', 'HDL (mg/dL)', 'Estimated LDL (mg/dL)', 'Fasting Blood Sugar (mg/dL)']
lifestyle_cols = ['Smoking Status', 'Diabetes Status', 'Physical Activity Level', 'Family History of CVD']
target_cols = ['CVD Risk Level', 'CVD Risk Score']
derived_cols = ['age_band']
flag_cols = [c for c in df_raw.columns if c.endswith('_was_imputed')]

df = df_raw.copy()

# ==========================================================
# 5. MODEL PIPELINE -- TRAIN LOCALLY (with S3 cache)
# ==========================================================
cat_features = ['Sex', 'Smoking Status', 'Diabetes Status', 'Physical Activity Level', 'Family History of CVD']
num_features = ['Age', 'BMI', 'Systolic BP', 'Diastolic BP', 'Total Cholesterol (mg/dL)', 'HDL (mg/dL)', 'Fasting Blood Sugar (mg/dL)']
feature_cols = num_features + cat_features

MODEL_KEYS = {
    'clf': f"{S3_MODEL_PREFIX}/stage1_clf.joblib",
    'reg': f"{S3_MODEL_PREFIX}/stage2_reg.joblib",
    'label_encoders': f"{S3_MODEL_PREFIX}/label_encoders.joblib",
    'target_le': f"{S3_MODEL_PREFIX}/target_le.joblib",
}

def _download_joblib(key):
    body = s3_client.get_object(Bucket=S3_BUCKET, Key=key)['Body'].read()
    return joblib.load(io.BytesIO(body))

def _upload_joblib(obj, key):
    buf = io.BytesIO()
    joblib.dump(obj, buf)
    buf.seek(0)
    s3_client.put_object(Bucket=S3_BUCKET, Key=key, Body=buf.getvalue())

def load_or_train_model(df_model_source):
    """Try loading a previously trained model from S3 first (fast reconnect);
    otherwise train fresh in this session and cache the result back to S3."""
    try:
        print("Checking S3 for a previously trained model...")
        clf_loaded = _download_joblib(MODEL_KEYS['clf'])
        reg_loaded = _download_joblib(MODEL_KEYS['reg'])
        label_encoders_loaded = _download_joblib(MODEL_KEYS['label_encoders'])
        target_le_loaded = _download_joblib(MODEL_KEYS['target_le'])
        print("✅ Loaded existing trained model from S3 -- skipping retraining.")
        return clf_loaded, reg_loaded, label_encoders_loaded, target_le_loaded
    except ClientError:
        print("No cached model found in S3. Training a fresh model in this session...")
    except Exception as e:
        print(f"⚠️ Could not load cached model ({e}). Training a fresh model instead.")

    label_encoders_new = {}
    df_model = df_model_source.copy()
    for col in cat_features:
        le = LabelEncoder()
        df_model[col] = le.fit_transform(df_model[col].astype(str))
        label_encoders_new[col] = le

    target_le_new = LabelEncoder()
    df_model['CVD_Risk_Level_Encoded'] = target_le_new.fit_transform(df_model['CVD Risk Level'])

    X = df_model[feature_cols]
    y_class = df_model['CVD_Risk_Level_Encoded']
    y_reg = df_model['CVD Risk Score']

    X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
        X, y_class, y_reg, test_size=0.2, random_state=42
    )

    clf_new = HistGradientBoostingClassifier(random_state=42)
    clf_new.fit(X_train, y_class_train)

    X_train_reg = X_train.copy()
    X_train_reg['CVD_Risk_Level_Signal'] = y_class_train
    X_test_reg = X_test.copy()
    X_test_reg['CVD_Risk_Level_Signal'] = clf_new.predict(X_test)

    reg_new = HistGradientBoostingRegressor(random_state=42)
    reg_new.fit(X_train_reg, y_reg_train)

    # Stash test split on the objects' closure for later reporting -- simplest
    # is to just recompute metrics where needed below via module-level vars.
    global _X_test_reg, _y_reg_test
    _X_test_reg, _y_reg_test = X_test_reg, y_reg_test

    print("Caching newly trained model artifacts back to S3 for future sessions...")
    try:
        _upload_joblib(clf_new, MODEL_KEYS['clf'])
        _upload_joblib(reg_new, MODEL_KEYS['reg'])
        _upload_joblib(label_encoders_new, MODEL_KEYS['label_encoders'])
        _upload_joblib(target_le_new, MODEL_KEYS['target_le'])
        print(f"✅ Model artifacts cached to s3://{S3_BUCKET}/{S3_MODEL_PREFIX}/")
    except Exception as e:
        print(f"⚠️ Could not cache model to S3 ({e}). Continuing with in-memory model only.")

    return clf_new, reg_new, label_encoders_new, target_le_new

_X_test_reg, _y_reg_test = None, None
clf, reg, label_encoders, target_le = load_or_train_model(df)

# If the model was loaded from S3 cache (not freshly trained), build a test
# split now purely for the Predictive Analytics tab's reported metrics.
if _X_test_reg is None:
    df_model = df.copy()
    for col in cat_features:
        df_model[col] = label_encoders[col].transform(df_model[col].astype(str))
    df_model['CVD_Risk_Level_Encoded'] = target_le.transform(df_model['CVD Risk Level'])
    X = df_model[feature_cols]
    y_reg = df_model['CVD Risk Score']
    y_class_for_split = df_model['CVD_Risk_Level_Encoded']
    X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
        X, y_class_for_split, y_reg, test_size=0.2, random_state=42
    )
    X_test_reg = X_test.copy()
    X_test_reg['CVD_Risk_Level_Signal'] = clf.predict(X_test)
    _X_test_reg, _y_reg_test = X_test_reg, y_reg_test

# K-Means Clustering
cluster_cols = ['Age', 'BMI', 'Systolic BP', 'Diastolic BP', 'Total Cholesterol (mg/dL)', 'Fasting Blood Sugar (mg/dL)']
scaler_cluster = StandardScaler()
X_cluster_scaled = scaler_cluster.fit_transform(df[cluster_cols].fillna(df[cluster_cols].median()))
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['Cluster_Segment'] = kmeans.fit_predict(X_cluster_scaled)

# ==========================================================
# 6. GRADIO INTERFACE BUILD
# ==========================================================
with gr.Blocks(title="Cardiovascular Disease (CVD) Analytics System") as demo:
    gr.Markdown("# 🏥 CVD Risk Stratification & Clinical Analytics Portal")
    gr.Markdown("Connected directly to the AWS S3 Data Lake (Medallion Architecture). Model trains in-session.")

    # TAB 1: EXECUTIVE OVERVIEW
    with gr.Tab("Executive Overview & Lineage"):
        gr.Markdown("### 📊 Pipeline Health & Data Lineage Audit")
        with gr.Row():
            gr.Textbox(value=f"{len(df):,}", label="Total Screened Records", interactive=False)
            gr.Textbox(value=f"{df['CVD Risk Score'].mean():.2f}", label="Average Patient Risk Score", interactive=False)
            gr.Textbox(value=f"{(df['CVD Risk Level']=='HIGH').mean()*100:.1f}%", label="High Risk Prevalence", interactive=False)

        gr.Markdown("#### Data Quality Imputation Audit (AWS Glue ETL Flags)")
        if flag_cols:
            impute_summary = df[flag_cols].mean().reset_index()
            impute_summary.columns = ['Imputed Attribute Flag', 'Imputation Rate (%)']
            impute_summary['Imputation Rate (%)'] = (impute_summary['Imputation Rate (%)'] * 100).round(2)
            gr.DataFrame(impute_summary)

    # TAB 2: DESCRIPTIVE EXPLORATION
    with gr.Tab("Descriptive Exploration"):
        gr.Markdown("### 📈 Biometric Correlations")
        def plot_corr():
            fig, ax = plt.subplots(figsize=(8, 5))
            sns.heatmap(df[num_features + ['CVD Risk Score']].corr(), annot=True, fmt=".2f", cmap="coolwarm", ax=ax)
            plt.title("Pearson Correlation Matrix")
            plt.tight_layout()
            return fig
        gr.Plot(plot_corr)

    # TAB 3: CLUSTERING
    with gr.Tab("Patient Profiling (K-Means)"):
        gr.Markdown("### 🧬 Unsupervised Clinical Cohorts")
        def eval_clusters(k_val):
            km = KMeans(n_clusters=k_val, random_state=42, n_init=10)
            labels = km.fit_predict(X_cluster_scaled)
            sil = silhouette_score(X_cluster_scaled, labels)

            fig, ax = plt.subplots(figsize=(7, 4))
            sns.scatterplot(x=df['Age'], y=df['BMI'], hue=labels, palette='tab10', ax=ax)
            plt.title(f"Patient Segmentation (k={k_val}) - Silhouette Score: {sil:.3f}")
            return fig
        k_slider = gr.Slider(minimum=2, maximum=8, value=4, step=1, label="Select Cluster Count (k)")
        cluster_plot = gr.Plot()
        k_slider.change(eval_clusters, inputs=k_slider, outputs=cluster_plot)

    # TAB 4: PREDICTIVE ANALYTICS
    with gr.Tab("Predictive Analytics"):
        gr.Markdown("### 🎯 Model Performance & Hypothesis Testing")
        preds = reg.predict(_X_test_reg)
        r2 = r2_score(_y_reg_test, preds)
        mae = mean_absolute_error(_y_reg_test, preds)
        rmse = np.sqrt(mean_squared_error(_y_reg_test, preds))

        gr.Markdown(f"**Test Set R² Score:** {r2:.3f} | **MAE:** {mae:.2f} | **RMSE:** {rmse:.2f}")

        def plot_hypothesis():
            smokers = df[df['Smoking Status']=='Y']['CVD Risk Score']
            non_smokers = df[df['Smoking Status']=='N']['CVD Risk Score']
            t_stat, p_val = stats.ttest_ind(smokers, non_smokers, equal_var=False)

            fig, ax = plt.subplots(figsize=(6, 3.5))
            sns.boxplot(x='Smoking Status', y='CVD Risk Score', data=df, ax=ax, palette='Set2')
            plt.title(f"Smoking vs. Risk Score (Welch's t-test p-val: {p_val:.4e})")
            return fig
        gr.Plot(plot_hypothesis)

    # TAB 5: PATIENT SIMULATOR (LOCAL IN-SESSION MODEL)
    with gr.Tab("Patient Simulator (Inference)"):
        gr.Markdown("### 🩺 Real-Time Clinical Risk Score Assessment")
        gr.Markdown("_Predictions run against the model trained in this Colab session (or loaded from the S3 cache above)._")

        with gr.Row():
            age_in = gr.Number(value=55, label="Age")
            sex_in = gr.Dropdown(choices=["M", "F"], value="M", label="Sex")
            bmi_in = gr.Number(value=28.4, label="BMI")
            sys_in = gr.Number(value=138, label="Systolic BP")
            dia_in = gr.Number(value=88, label="Diastolic BP")
        with gr.Row():
            chol_in = gr.Number(value=215, label="Total Cholesterol (mg/dL)")
            hdl_in = gr.Number(value=42, label="HDL (mg/dL)")
            fbs_in = gr.Number(value=110, label="Fasting Blood Sugar (mg/dL)")
            smoke_in = gr.Dropdown(choices=["Y", "N"], value="N", label="Smoking Status")
            diab_in = gr.Dropdown(choices=["Y", "N"], value="N", label="Diabetes Status")
            act_in = gr.Dropdown(choices=["Low", "Moderate", "High"], value="Moderate", label="Physical Activity")
            fam_in = gr.Dropdown(choices=["Y", "N"], value="N", label="Family History of CVD")

        calc_btn = gr.Button("Calculate Patient CVD Risk", variant="primary")

        out_cluster = gr.Textbox(label="Assigned Cluster Cohort")
        out_risk_level = gr.Textbox(label="Predicted CVD Risk Level (Stage 1)")
        out_risk_score = gr.Number(label="Predicted Quantified CVD Risk Score (Stage 2)")

        def run_inference(age, sex, bmi, sys_bp, dia_bp, chol, hdl, fbs, smoke, diab, act, fam):
            # Cluster assignment
            sample_scaled = scaler_cluster.transform([[age, bmi, sys_bp, dia_bp, chol, fbs]])
            cluster_id = kmeans.predict(sample_scaled)[0]

            # Local in-session model inference (no external endpoint)
            input_dict = {
                'Age': age, 'BMI': bmi, 'Systolic BP': sys_bp, 'Diastolic BP': dia_bp,
                'Total Cholesterol (mg/dL)': chol, 'HDL (mg/dL)': hdl, 'Fasting Blood Sugar (mg/dL)': fbs,
                'Sex': label_encoders['Sex'].transform([sex])[0],
                'Smoking Status': label_encoders['Smoking Status'].transform([smoke])[0],
                'Diabetes Status': label_encoders['Diabetes Status'].transform([diab])[0],
                'Physical Activity Level': label_encoders['Physical Activity Level'].transform([act])[0],
                'Family History of CVD': label_encoders['Family History of CVD'].transform([fam])[0]
            }
            input_df = pd.DataFrame([input_dict])[feature_cols]
            pred_class_enc = clf.predict(input_df)[0]
            pred_class_str = target_le.inverse_transform([pred_class_enc])[0]

            input_df_reg = input_df.copy()
            input_df_reg['CVD_Risk_Level_Signal'] = pred_class_enc
            pred_score = reg.predict(input_df_reg)[0]

            return f"Cluster {cluster_id}", pred_class_str, round(float(pred_score), 2)

        calc_btn.click(
            run_inference,
            inputs=[age_in, sex_in, bmi_in, sys_in, dia_in, chol_in, hdl_in, fbs_in, smoke_in, diab_in, act_in, fam_in],
            outputs=[out_cluster, out_risk_level, out_risk_score]
        )

# Launch Gradio App with Shareable URL
demo.launch(share=True)
